// Affinity CRM integration.
// Real REST calls if AFFINITY_API_KEY is set; otherwise dry-run mode that returns the exact
// request bodies we WOULD send. Either way the demo can show the integration story.
//
// Affinity v2 docs: https://api.affinity.co/v2 (basic auth: empty username, key as password).

import { Hono } from 'hono';
import { db, schema } from '../db/index.ts';
import { eq } from 'drizzle-orm';
import { z } from 'zod';

export const affinityRoutes = new Hono();

const KEY = () => process.env.AFFINITY_API_KEY || '';
const isDryRun = () => KEY().length === 0;

function authHeader() {
  // Affinity uses basic auth with empty user + key as password
  return `Basic ${Buffer.from(`:${KEY()}`).toString('base64')}`;
}

affinityRoutes.get('/status', (c) => {
  return c.json({
    connected: !isDryRun(),
    mode: isDryRun() ? 'dry_run' : 'live',
    talentListId: process.env.AFFINITY_LIST_ID_TALENT || null,
    startupsListId: process.env.AFFINITY_LIST_ID_STARTUPS || null,
  });
});

// PUSH: when a Nucleus staffer approves a match, attach a Note to both records and add them to a "Hackathon Matched" list.
const Push = z.object({ talentId: z.string(), startupId: z.string(), summary: z.string() });

affinityRoutes.post('/push-match', async (c) => {
  const body = Push.parse(await c.req.json());
  const [t] = await db.select().from(schema.talent).where(eq(schema.talent.id, body.talentId));
  const [s] = await db.select().from(schema.startup).where(eq(schema.startup.id, body.startupId));
  if (!t || !s) return c.json({ error: 'not found' }, 404);

  const noteContent = `Nucleus AI match: ${t.name} ↔ ${s.name}\n\n${body.summary}\n\nGenerated by nucleus.kokomo.quest`;

  const requests = [
    {
      label: 'Create Note attached to person',
      method: 'POST',
      url: 'https://api.affinity.co/notes',
      body: { content: noteContent, person_ids: ['<affinity person id resolved by email>'] },
    },
    {
      label: 'Create Note attached to organization',
      method: 'POST',
      url: 'https://api.affinity.co/notes',
      body: { content: noteContent, organization_ids: ['<affinity org id resolved by name>'] },
    },
    {
      label: 'Add to "Hackathon Matched" list',
      method: 'POST',
      url: 'https://api.affinity.co/v2/lists/<HACKATHON_MATCHED_LIST_ID>/list-entries',
      body: { entityId: '<affinity entity id>', entityType: 'organization' },
    },
  ];

  if (isDryRun()) {
    return c.json({ mode: 'dry_run', requests });
  }

  // Live mode — make the actual calls. We resolve person/org IDs by lookup.
  const headers = { 'Content-Type': 'application/json', Authorization: authHeader() };
  const results: Array<Record<string, unknown>> = [];

  // 1. Resolve org by name
  const orgSearch = await fetch(`https://api.affinity.co/organizations?term=${encodeURIComponent(s.name)}`, { headers });
  const orgs = (await orgSearch.json()) as { organizations?: { id: number; name: string }[] };
  const orgId = orgs.organizations?.[0]?.id;

  // 2. Resolve person by email if available
  let personId: number | undefined;
  if (t.email) {
    const personSearch = await fetch(`https://api.affinity.co/persons?term=${encodeURIComponent(t.email)}`, { headers });
    const persons = (await personSearch.json()) as { persons?: { id: number }[] };
    personId = persons.persons?.[0]?.id;
  }

  // 3. Create note(s)
  if (personId) {
    const r = await fetch('https://api.affinity.co/notes', {
      method: 'POST', headers,
      body: JSON.stringify({ content: noteContent, person_ids: [personId] }),
    });
    results.push({ label: 'note_person', status: r.status, body: await r.json().catch(() => null) });
  }
  if (orgId) {
    const r = await fetch('https://api.affinity.co/notes', {
      method: 'POST', headers,
      body: JSON.stringify({ content: noteContent, organization_ids: [orgId] }),
    });
    results.push({ label: 'note_org', status: r.status, body: await r.json().catch(() => null) });
  }

  return c.json({ mode: 'live', personId, orgId, results });
});

// PULL: import a list of persons/orgs from Affinity and store them as talent/startup stubs.
affinityRoutes.get('/pull-preview', async (c) => {
  if (isDryRun()) {
    return c.json({
      mode: 'dry_run',
      sample: {
        talent: [{ id: 'aff_1', name: '<from Affinity persons>', email: '<email>' }],
        startups: [{ id: 'aff_2', name: '<from Affinity organizations>', website: '<website>' }],
      },
      note: 'Set AFFINITY_API_KEY and AFFINITY_LIST_ID_* in env to enable live pull.',
    });
  }
  const headers = { Authorization: authHeader() };
  const persons = await fetch('https://api.affinity.co/persons?page_size=20', { headers }).then((r) => r.json());
  const orgs = await fetch('https://api.affinity.co/organizations?page_size=20', { headers }).then((r) => r.json());
  return c.json({ mode: 'live', persons, orgs });
});
