// Synthetic Utah-flavored startup catalog. Names invented; archetypes inspired by
// real Utah deep-tech (neural-prosthetic and bio-computer flagships called out by Nucleus).

export interface SeedStartup {
  id: string;
  name: string;
  oneliner: string;
  description: string;
  location: string;
  website: string;
  sector: 'life_sciences' | 'ai' | 'defense' | 'cyber' | 'energy' | 'advanced_manufacturing' | 'fintech' | 'software';
  origin: 'u_of_u_lab' | 'byu_lab' | 'usu_lab' | 'bootstrapped' | 'corporate_spinout';
  trl: number;
  fundingStage: 'idea' | 'pre_seed' | 'seed' | 'series_a' | 'series_b' | 'growth';
  fundingRaisedUsd: number;
  fundingSources: string[];
  immediateNeeds: string[];
  missionTags: string[];
  utahRoots: string[];
}

export const seedStartups: SeedStartup[] = [
  {
    id: 'st_neurotouch',
    name: 'NeuroTouch Bio',
    oneliner: 'Implantable neural interface that lets prosthetics feel touch and texture.',
    description:
      "Spun out of the U of U bioengineering lab, NeuroTouch builds an implantable neural interface for upper-limb prosthetics. The device closes the sensory loop — patients don't just control the prosthetic, they feel pressure, temperature, and texture through it. Currently in pre-clinical trials with three amputees at the U of U hospital. Targeting an FDA Breakthrough Device pathway and a Class III submission within 18 months.",
    location: 'Salt Lake City, UT',
    website: 'https://neurotouch.bio',
    sector: 'life_sciences',
    origin: 'u_of_u_lab',
    trl: 5,
    fundingStage: 'seed',
    fundingRaisedUsd: 2_400_000,
    fundingSources: ['nih', 'nsf_sbir', 'angel'],
    immediateNeeds: ['ceo', 'regulatory', 'biz_dev', 'advisor'],
    missionTags: ['patient_outcomes', 'deep_science', 'hard_tech'],
    utahRoots: ['u_of_u'],
  },
  {
    id: 'st_silicell',
    name: 'SiliCell Compute',
    oneliner: 'Bio-computer chips: silicon scaffolds populated with cultured neuronal tissue.',
    description:
      "BYU + U of U joint spinout developing a hybrid compute substrate — engineered silicon scaffolds populated with stem-cell-derived neuronal tissue. Pattern-recognition workloads run with ~1/100th the energy of equivalent GPU operations. Two patents filed. Looking for a CTO with deep neuromorphic or ASIC experience and a commercial lead who can navigate biotech-meets-semiconductor go-to-market.",
    location: 'Provo, UT',
    website: 'https://silicell.compute',
    sector: 'advanced_manufacturing',
    origin: 'byu_lab',
    trl: 3,
    fundingStage: 'pre_seed',
    fundingRaisedUsd: 750_000,
    fundingSources: ['nsf_sbir', 'grant'],
    immediateNeeds: ['cto', 'biz_dev', 'engineer', 'advisor'],
    missionTags: ['hard_tech', 'deep_science', 'sustainability'],
    utahRoots: ['byu', 'u_of_u'],
  },
  {
    id: 'st_aerolith',
    name: 'Aerolith Defense',
    oneliner: 'Autonomous swarm logistics for contested-environment resupply.',
    description:
      "Hill AFB-adjacent defense startup building a low-cost autonomous swarm for last-mile resupply in contested environments. Won Phase II SBIR from AFWERX in 2025. Need a VP Sales with DoD program-office relationships and a regulatory/ITAR specialist before the next prime contract.",
    location: 'Ogden, UT',
    website: 'https://aerolith.defense',
    sector: 'defense',
    origin: 'corporate_spinout',
    trl: 6,
    fundingStage: 'series_a',
    fundingRaisedUsd: 11_000_000,
    fundingSources: ['venture', 'nsf_sbir', 'grant'],
    immediateNeeds: ['sales', 'regulatory', 'engineer'],
    missionTags: ['defense', 'hard_tech'],
    utahRoots: ['silicon_slopes'],
  },
  {
    id: 'st_kestrel',
    name: 'Kestrel Cyber',
    oneliner: 'Identity-attack telemetry for non-human (agent) accounts.',
    description:
      "Bootstrapped Lehi-based cyber startup focused on agentic-identity threat detection — specifically tracking malicious or hijacked AI agents acting on behalf of users. Three founding engineers ex-Qualtrics. Looking for a head of marketing and a fractional CFO before raising a seed.",
    location: 'Lehi, UT',
    website: 'https://kestrel.cyber',
    sector: 'cyber',
    origin: 'bootstrapped',
    trl: 7,
    fundingStage: 'pre_seed',
    fundingRaisedUsd: 0,
    fundingSources: [],
    immediateNeeds: ['marketing', 'cfo', 'sales'],
    missionTags: ['hard_tech', 'productivity'],
    utahRoots: ['silicon_slopes'],
  },
  {
    id: 'st_arrasti',
    name: 'Arrasti Energy',
    oneliner: 'Geothermal-loop heat exchangers for industrial decarbonization.',
    description:
      "Utah State spinout commercializing low-cost closed-loop geothermal heat exchangers for cement and ag-processing facilities. DOE Geothermal Technologies Office grant of $3.2M. Pilot deployment with a Cache Valley dairy processor in Q3. Needs a CEO comfortable with utility-scale capital sales cycles.",
    location: 'Logan, UT',
    website: 'https://arrasti.energy',
    sector: 'energy',
    origin: 'usu_lab',
    trl: 6,
    fundingStage: 'seed',
    fundingRaisedUsd: 4_800_000,
    fundingSources: ['grant', 'venture'],
    immediateNeeds: ['ceo', 'sales', 'regulatory'],
    missionTags: ['sustainability', 'hard_tech'],
    utahRoots: ['usu'],
  },
  {
    id: 'st_lumalign',
    name: 'Lumalign Therapeutics',
    oneliner: 'mRNA-engineered targeted radiotherapy for pediatric brain tumors.',
    description:
      "Translational oncology spinout from the U of U Huntsman Cancer Institute. mRNA-conjugated radioligand approach for diffuse midline glioma. Pre-IND meeting with FDA scheduled. Needs a chief medical officer and seasoned regulatory counsel for the upcoming Phase 1 IND filing.",
    location: 'Salt Lake City, UT',
    website: 'https://lumalign.bio',
    sector: 'life_sciences',
    origin: 'u_of_u_lab',
    trl: 4,
    fundingStage: 'seed',
    fundingRaisedUsd: 6_500_000,
    fundingSources: ['nih', 'venture'],
    immediateNeeds: ['cmo', 'regulatory', 'advisor'],
    missionTags: ['patient_outcomes', 'deep_science'],
    utahRoots: ['u_of_u'],
  },
  {
    id: 'st_terraform',
    name: 'TerraForm Ag',
    oneliner: 'AI-tuned regenerative seeding plans for arid Western rangelands.',
    description:
      "BYU plant-and-wildlife science spinout. Computer-vision + soil-microbiome sensing produces species-level seeding prescriptions for BLM and tribal rangeland restoration projects. Active pilots in Wayne and San Juan counties. Wants a biz-dev lead familiar with federal land contracts.",
    location: 'Provo, UT',
    website: 'https://terraform.ag',
    sector: 'ai',
    origin: 'byu_lab',
    trl: 6,
    fundingStage: 'seed',
    fundingRaisedUsd: 3_100_000,
    fundingSources: ['grant', 'venture'],
    immediateNeeds: ['biz_dev', 'sales', 'engineer'],
    missionTags: ['sustainability', 'hard_tech'],
    utahRoots: ['byu'],
  },
  {
    id: 'st_provident',
    name: 'Provident Underwriting',
    oneliner: 'AI underwriting for community bank commercial loans.',
    description:
      "Silicon Slopes-based fintech automating underwriting for sub-$5M community-bank commercial loans. Three pilot banks live in Utah and Idaho. Founder is ex-Zions Bancorporation. Wants a head of sales who has sold into community banks before, and a senior frontend engineer.",
    location: 'Lehi, UT',
    website: 'https://provident.fyi',
    sector: 'fintech',
    origin: 'bootstrapped',
    trl: 8,
    fundingStage: 'series_a',
    fundingRaisedUsd: 14_000_000,
    fundingSources: ['venture'],
    immediateNeeds: ['sales', 'engineer', 'marketing'],
    missionTags: ['productivity'],
    utahRoots: ['silicon_slopes'],
  },
  {
    id: 'st_palisade',
    name: 'Palisade Robotics',
    oneliner: 'Bimanual industrial robots that learn by watching one technician demo.',
    description:
      "USU mechanical-engineering spinout building a foundation-model-driven bimanual robot for kitting and assembly tasks. One-shot imitation from a single technician demonstration. Targeting Utah aerospace and medical-device contract manufacturers. Wants a fractional COO who has scaled hardware ops.",
    location: 'North Logan, UT',
    website: 'https://palisade.robotics',
    sector: 'advanced_manufacturing',
    origin: 'usu_lab',
    trl: 4,
    fundingStage: 'pre_seed',
    fundingRaisedUsd: 1_200_000,
    fundingSources: ['nsf_sbir', 'angel'],
    immediateNeeds: ['coo', 'engineer', 'sales'],
    missionTags: ['hard_tech', 'productivity'],
    utahRoots: ['usu'],
  },
  {
    id: 'st_cipherframe',
    name: 'Cipherframe',
    oneliner: 'Confidential-compute audit toolkit for HIPAA-grade ML pipelines.',
    description:
      "Cybersecurity startup founded by two ex-Domo engineers. Toolkit auditing confidential-compute environments (TEEs, SGX) for healthcare ML pipelines. Three Utah-based hospital systems in pilot. Needs a CISO advisor and a healthcare-focused biz-dev lead.",
    location: 'American Fork, UT',
    website: 'https://cipherframe.io',
    sector: 'cyber',
    origin: 'bootstrapped',
    trl: 7,
    fundingStage: 'seed',
    fundingRaisedUsd: 3_500_000,
    fundingSources: ['venture', 'angel'],
    immediateNeeds: ['biz_dev', 'advisor', 'engineer'],
    missionTags: ['patient_outcomes', 'productivity'],
    utahRoots: ['silicon_slopes'],
  },
  {
    id: 'st_pluvial',
    name: 'Pluvial Climate',
    oneliner: 'Hyperlocal monsoon-flood prediction for SW US municipalities.',
    description:
      "U of U atmospheric-sciences spinout. Hyperlocal flood prediction calibrated to the SW US monsoon regime — useful for Wasatch Front cities planning stormwater infrastructure. Currently a pilot with Salt Lake County and the city of St. George.",
    location: 'Salt Lake City, UT',
    website: 'https://pluvial.climate',
    sector: 'ai',
    origin: 'u_of_u_lab',
    trl: 5,
    fundingStage: 'pre_seed',
    fundingRaisedUsd: 600_000,
    fundingSources: ['grant', 'angel'],
    immediateNeeds: ['ceo', 'biz_dev', 'engineer'],
    missionTags: ['sustainability'],
    utahRoots: ['u_of_u'],
  },
  {
    id: 'st_quartzline',
    name: 'Quartzline Photonics',
    oneliner: 'Compact LIDAR for autonomous mining and quarry operations.',
    description:
      "U of U electrical-engineering spinout building a ruggedized photonic-integrated-circuit LIDAR for mining and quarry vehicles. Two-year LOI with Rio Tinto Kennecott. Capital-intensive — needs a CFO experienced in deep-tech bridge rounds.",
    location: 'Salt Lake City, UT',
    website: 'https://quartzline.photonics',
    sector: 'advanced_manufacturing',
    origin: 'u_of_u_lab',
    trl: 5,
    fundingStage: 'seed',
    fundingRaisedUsd: 5_200_000,
    fundingSources: ['venture', 'grant'],
    immediateNeeds: ['cfo', 'engineer', 'sales'],
    missionTags: ['hard_tech'],
    utahRoots: ['u_of_u'],
  },
  {
    id: 'st_stillwater',
    name: 'Stillwater Bioscience',
    oneliner: 'Microfluidic at-home assays for early hereditary-cancer screening.',
    description:
      "BYU chemistry spinout. Microfluidic at-home assay reading saliva for hereditary-cancer markers (BRCA1, Lynch). Validated against clinical-grade qPCR in a 200-patient study at Intermountain Health.",
    location: 'Provo, UT',
    website: 'https://stillwater.bio',
    sector: 'life_sciences',
    origin: 'byu_lab',
    trl: 5,
    fundingStage: 'seed',
    fundingRaisedUsd: 4_000_000,
    fundingSources: ['nih', 'venture'],
    immediateNeeds: ['ceo', 'regulatory', 'marketing'],
    missionTags: ['patient_outcomes', 'deep_science'],
    utahRoots: ['byu'],
  },
  {
    id: 'st_argosvine',
    name: 'Argos Vine',
    oneliner: 'Drone-based phenotyping for high-altitude wine grapes.',
    description:
      "USU plant-sciences spinout. Drone + multispectral phenotyping pipeline for vineyard managers, with a niche focus on cold-climate / high-elevation cultivars. Eight pilot vineyards across UT, ID, and CO.",
    location: 'Logan, UT',
    website: 'https://argosvine.farm',
    sector: 'ai',
    origin: 'usu_lab',
    trl: 7,
    fundingStage: 'seed',
    fundingRaisedUsd: 2_100_000,
    fundingSources: ['grant', 'angel'],
    immediateNeeds: ['sales', 'engineer'],
    missionTags: ['sustainability'],
    utahRoots: ['usu'],
  },
  {
    id: 'st_sentry',
    name: 'Sentry SaaS',
    oneliner: 'Vertical software for franchise commercial-cleaning operations.',
    description:
      "Bootstrapped vertical SaaS for franchise cleaning operations: scheduling, payroll, customer portal. 90 customers, $2M ARR, profitable. Founder wants to step into chairman role and bring in a CEO to scale.",
    location: 'Bluffdale, UT',
    website: 'https://sentry.saas',
    sector: 'software',
    origin: 'bootstrapped',
    trl: 9,
    fundingStage: 'growth',
    fundingRaisedUsd: 0,
    fundingSources: [],
    immediateNeeds: ['ceo', 'sales', 'marketing'],
    missionTags: ['productivity'],
    utahRoots: ['silicon_slopes'],
  },
  {
    id: 'st_meadowlark',
    name: 'Meadowlark Wealth',
    oneliner: 'Alt-asset accounting and reporting for Utah family offices.',
    description:
      "Park City fintech serving Utah family offices and small RIAs. Software handles complex alt-asset structures (LP interests, QOZ funds). Five paid customers. Needs a head of customer success and a part-time advisor with family-office relationships.",
    location: 'Park City, UT',
    website: 'https://meadowlark.wealth',
    sector: 'fintech',
    origin: 'bootstrapped',
    trl: 8,
    fundingStage: 'pre_seed',
    fundingRaisedUsd: 0,
    fundingSources: [],
    immediateNeeds: ['biz_dev', 'advisor', 'sales'],
    missionTags: ['productivity'],
    utahRoots: ['park_city'],
  },
  {
    id: 'st_apex',
    name: 'Apex Reactor',
    oneliner: 'Modular fission micro-reactors for remote DoD installations.',
    description:
      "Defense-energy startup developing a 1MW fission micro-reactor purpose-built for off-grid DoD installations. Supported by an NDA with INL. Needs a chief regulatory officer comfortable with NRC pre-application engagement.",
    location: 'Idaho Falls, ID (UT-tied)',
    website: 'https://apex.reactor',
    sector: 'energy',
    origin: 'corporate_spinout',
    trl: 4,
    fundingStage: 'series_a',
    fundingRaisedUsd: 22_000_000,
    fundingSources: ['venture', 'grant'],
    immediateNeeds: ['regulatory', 'engineer', 'biz_dev'],
    missionTags: ['hard_tech', 'defense', 'sustainability'],
    utahRoots: ['silicon_slopes'],
  },
  {
    id: 'st_helio',
    name: 'Helio Trial Ops',
    oneliner: 'AI-driven clinical trial recruitment for rare pediatric oncology.',
    description:
      "U of U Huntsman + Primary Children's Hospital partnership. AI-driven recruitment workflow that surfaces eligible pediatric-oncology trial candidates from EHRs while preserving HIPAA boundaries. Needs a regulatory affairs lead and a healthcare-vertical sales rep.",
    location: 'Salt Lake City, UT',
    website: 'https://helio.trials',
    sector: 'ai',
    origin: 'u_of_u_lab',
    trl: 6,
    fundingStage: 'seed',
    fundingRaisedUsd: 3_900_000,
    fundingSources: ['nih', 'venture'],
    immediateNeeds: ['regulatory', 'sales', 'engineer'],
    missionTags: ['patient_outcomes'],
    utahRoots: ['u_of_u'],
  },
];
