// Synthetic Utah-rooted talent pool spanning the full role taxonomy in the brief.

export interface SeedTalent {
  id: string;
  name: string;
  headline: string;
  bio: string;
  location: string;
  email: string;
  roleType: 'executive' | 'cofounder' | 'fractional' | 'engineer' | 'sales' | 'marketing' | 'student' | 'intern' | 'advisor' | 'mentor' | 'board' | 'investor' | 'service_provider';
  sectors: string[];
  skills: string[];
  functions: string[];
  availability: 'full_time' | 'fractional' | 'advisory' | 'internship' | 'mentor';
  stagePreference: string[];
  riskTolerance: 'low' | 'medium' | 'high';
  compShape: string[];
  missionTags: string[];
  affiliations: string[];
  yearsExperience: number;
}

export const seedTalent: SeedTalent[] = [
  // ---------- Executives / Cofounders ----------
  {
    id: 't_sarah_chen',
    name: 'Sarah Chen',
    headline: 'Ex-Recursion VP Regulatory · led 2 FDA Class III submissions',
    bio: "Spent 9 years at Recursion taking imaging-AI-derived therapeutics through pre-clin and into early clinical. Personally led two FDA Class III device submissions and one IND. Looking for an early-stage life-sciences CEO seat where the regulatory path is the rate-limiting step.",
    location: 'Salt Lake City, UT',
    email: 'sarah.chen@example.com',
    roleType: 'executive',
    sectors: ['life_sciences'],
    skills: ['FDA Class III', 'IND filings', 'regulatory strategy', 'pre-clinical operations', 'team building', 'fundraising'],
    functions: ['regulatory', 'operations', 'finance'],
    availability: 'full_time',
    stagePreference: ['seed', 'series_a'],
    riskTolerance: 'high',
    compShape: ['salary', 'equity'],
    missionTags: ['patient_outcomes', 'deep_science'],
    affiliations: ['recursion', 'u_of_u'],
    yearsExperience: 14,
  },
  {
    id: 't_devon_park',
    name: 'Devon Park',
    headline: 'Defense systems exec · 12 yrs Lockheed + Sarcos · TS/SCI',
    bio: "Sarcos VP of Programs through 2024, before that Lockheed Skunk Works. Led $40M+ DoD program acquisitions. TS/SCI cleared. Looking for a Utah defense startup where I can run programs end-to-end.",
    location: 'Ogden, UT',
    email: 'devon.park@example.com',
    roleType: 'executive',
    sectors: ['defense', 'advanced_manufacturing'],
    skills: ['DoD acquisition', 'program management', 'ITAR', 'security clearances', 'systems engineering'],
    functions: ['operations', 'sales', 'regulatory'],
    availability: 'full_time',
    stagePreference: ['series_a', 'series_b'],
    riskTolerance: 'medium',
    compShape: ['salary', 'equity'],
    missionTags: ['defense', 'hard_tech'],
    affiliations: ['sarcos', 'silicon_slopes'],
    yearsExperience: 18,
  },
  {
    id: 't_priya_anand',
    name: 'Priya Anand',
    headline: 'Founder/CEO (1 exit) · neuro-tech · U of U bioE PhD',
    bio: "Founded and exited a neuro-stim startup to Boston Scientific in 2022. PhD bioengineering U of U. Looking to cofound the next thing — neural interfaces, deep-tissue imaging, or anything where the science is hard.",
    location: 'Salt Lake City, UT',
    email: 'priya.anand@example.com',
    roleType: 'cofounder',
    sectors: ['life_sciences'],
    skills: ['neural interfaces', 'medical device development', 'team building', 'fundraising', 'IP strategy', 'PhD bioengineering'],
    functions: ['product', 'operations', 'finance'],
    availability: 'full_time',
    stagePreference: ['idea', 'pre_seed', 'seed'],
    riskTolerance: 'high',
    compShape: ['equity'],
    missionTags: ['deep_science', 'patient_outcomes', 'hard_tech'],
    affiliations: ['u_of_u'],
    yearsExperience: 12,
  },
  {
    id: 't_tom_brigham',
    name: 'Tom Brigham',
    headline: 'Ex-Pluralsight COO · scaling B2B SaaS through $100M ARR',
    bio: "Ran ops at Pluralsight from $20M to $200M ARR. Now looking for a vertical-SaaS or fintech company in the $1-10M ARR range that needs a CEO/COO to take it through product-market-fit-to-scale.",
    location: 'Draper, UT',
    email: 'tom.brigham@example.com',
    roleType: 'executive',
    sectors: ['software', 'fintech'],
    skills: ['B2B SaaS scaling', 'sales operations', 'finance', 'org design', 'OKRs'],
    functions: ['operations', 'finance', 'sales'],
    availability: 'full_time',
    stagePreference: ['series_a', 'series_b', 'growth'],
    riskTolerance: 'medium',
    compShape: ['salary', 'equity'],
    missionTags: ['productivity'],
    affiliations: ['pluralsight', 'silicon_slopes'],
    yearsExperience: 17,
  },
  {
    id: 't_ana_morales',
    name: 'Ana Morales',
    headline: 'CFO · clean energy + project finance · DOE grant ninja',
    bio: "Ten years in project finance — wind, solar, geothermal. Closed $400M+ in DOE-backed transactions. Open to fractional CFO or full-time at a Utah energy hardtech company.",
    location: 'Park City, UT',
    email: 'ana.morales@example.com',
    roleType: 'executive',
    sectors: ['energy', 'advanced_manufacturing'],
    skills: ['project finance', 'DOE grants', 'tax-equity structuring', 'capital raising'],
    functions: ['finance', 'operations'],
    availability: 'fractional',
    stagePreference: ['seed', 'series_a', 'series_b'],
    riskTolerance: 'medium',
    compShape: ['salary', 'equity', 'hourly'],
    missionTags: ['sustainability', 'hard_tech'],
    affiliations: ['park_city'],
    yearsExperience: 12,
  },
  {
    id: 't_marcus_lee',
    name: 'Marcus Lee',
    headline: 'CMO · ex-Domo · scaled marketing through IPO',
    bio: "Domo CMO 2018-2023, scaled the team from 30 to 110 through IPO. Looking for a $20M+ ARR Utah company where I can come in fractional and replace myself in 18 months.",
    location: 'Lehi, UT',
    email: 'marcus.lee@example.com',
    roleType: 'fractional',
    sectors: ['software', 'fintech', 'cyber'],
    skills: ['demand gen', 'PLG', 'brand', 'analyst relations', 'category creation'],
    functions: ['operations', 'sales'],
    availability: 'fractional',
    stagePreference: ['series_a', 'series_b', 'growth'],
    riskTolerance: 'medium',
    compShape: ['salary', 'equity', 'hourly'],
    missionTags: ['productivity'],
    affiliations: ['domo', 'silicon_slopes'],
    yearsExperience: 16,
  },
  {
    id: 't_jenna_ryu',
    name: 'Jenna Ryu',
    headline: 'Fractional COO · hardware ops · ex-Sarcos, ex-Apple',
    bio: "Six years scaling hardware ops at Apple, three at Sarcos. Open to two fractional COO engagements with Utah hardtech companies. I will fix your bill of materials, your supplier audit, and your engineering-to-production handoff.",
    location: 'Provo, UT',
    email: 'jenna.ryu@example.com',
    roleType: 'fractional',
    sectors: ['advanced_manufacturing', 'defense', 'life_sciences'],
    skills: ['hardware ops', 'supply chain', 'BOM management', 'NPI', 'contract manufacturing'],
    functions: ['operations'],
    availability: 'fractional',
    stagePreference: ['seed', 'series_a'],
    riskTolerance: 'medium',
    compShape: ['salary', 'equity', 'hourly'],
    missionTags: ['hard_tech', 'productivity'],
    affiliations: ['sarcos', 'silicon_slopes'],
    yearsExperience: 13,
  },

  // ---------- Engineers ----------
  {
    id: 't_kai_wang',
    name: 'Kai Wang',
    headline: 'ML systems engineer · neuromorphic compute · BYU PhD candidate',
    bio: "Last-year BYU CS PhD on neuromorphic / spiking-NN compilers. Looking for a fractional or full-time founding-engineer role at a hard-tech compute company.",
    location: 'Provo, UT',
    email: 'kai.wang@example.com',
    roleType: 'engineer',
    sectors: ['ai', 'advanced_manufacturing'],
    skills: ['neuromorphic compute', 'compilers', 'CUDA', 'PyTorch', 'systems ML'],
    functions: ['engineering', 'product'],
    availability: 'full_time',
    stagePreference: ['idea', 'pre_seed', 'seed'],
    riskTolerance: 'high',
    compShape: ['equity', 'salary'],
    missionTags: ['hard_tech', 'deep_science'],
    affiliations: ['byu'],
    yearsExperience: 5,
  },
  {
    id: 't_olivia_park',
    name: 'Olivia Park',
    headline: 'Embedded systems engineer · medical implants · 7 yrs',
    bio: "Seven years building Class III implantable hardware (cardiac + neural). Last role at Boston Scientific. Want to be employee #5 at an early Utah medical device company.",
    location: 'Salt Lake City, UT',
    email: 'olivia.park@example.com',
    roleType: 'engineer',
    sectors: ['life_sciences'],
    skills: ['embedded firmware', 'IEC 60601', 'biocompatibility', 'wireless implant power', 'Class III hardware'],
    functions: ['engineering', 'regulatory'],
    availability: 'full_time',
    stagePreference: ['pre_seed', 'seed'],
    riskTolerance: 'high',
    compShape: ['salary', 'equity'],
    missionTags: ['patient_outcomes', 'deep_science'],
    affiliations: ['u_of_u'],
    yearsExperience: 7,
  },
  {
    id: 't_dani_oliveira',
    name: 'Dani Oliveira',
    headline: 'Senior full-stack · TypeScript / Postgres · ex-Qualtrics',
    bio: "Eight years senior engineer at Qualtrics. Want to join a small Utah B2B SaaS team and own a product surface end-to-end.",
    location: 'Provo, UT',
    email: 'dani.oliveira@example.com',
    roleType: 'engineer',
    sectors: ['software', 'fintech'],
    skills: ['TypeScript', 'React', 'Postgres', 'Hono', 'AWS', 'DX'],
    functions: ['engineering', 'product'],
    availability: 'full_time',
    stagePreference: ['seed', 'series_a'],
    riskTolerance: 'medium',
    compShape: ['salary', 'equity'],
    missionTags: ['productivity'],
    affiliations: ['qualtrics', 'silicon_slopes'],
    yearsExperience: 8,
  },
  {
    id: 't_yoel_haddad',
    name: 'Yoel Haddad',
    headline: 'Robotics SWE · ROS / motion planning · ex-Sarcos',
    bio: "Six years at Sarcos building motion-planning stacks for industrial exoskeletons. Want to join a small Utah robotics or autonomy company.",
    location: 'Salt Lake City, UT',
    email: 'yoel.haddad@example.com',
    roleType: 'engineer',
    sectors: ['advanced_manufacturing', 'defense'],
    skills: ['ROS2', 'motion planning', 'C++', 'sensor fusion', 'real-time systems'],
    functions: ['engineering'],
    availability: 'full_time',
    stagePreference: ['pre_seed', 'seed', 'series_a'],
    riskTolerance: 'high',
    compShape: ['salary', 'equity'],
    missionTags: ['hard_tech'],
    affiliations: ['sarcos', 'silicon_slopes'],
    yearsExperience: 6,
  },
  {
    id: 't_isabel_finch',
    name: 'Isabel Finch',
    headline: 'Photonics PhD · USU electro-optics · 4 yrs Northrop',
    bio: "Northrop electro-optics group then USU PhD on photonic-integrated circuits. Open to founding-engineer or technical-cofounder seats at a photonics-adjacent Utah startup.",
    location: 'Logan, UT',
    email: 'isabel.finch@example.com',
    roleType: 'engineer',
    sectors: ['advanced_manufacturing', 'defense'],
    skills: ['photonic integrated circuits', 'silicon photonics', 'electro-optics', 'GDS layout'],
    functions: ['engineering'],
    availability: 'full_time',
    stagePreference: ['pre_seed', 'seed'],
    riskTolerance: 'high',
    compShape: ['equity', 'salary'],
    missionTags: ['hard_tech', 'deep_science'],
    affiliations: ['usu'],
    yearsExperience: 8,
  },
  {
    id: 't_ben_okafor',
    name: 'Ben Okafor',
    headline: 'Security engineer · TEE / SGX · ex-Domo',
    bio: "Built confidential-compute toolchain at Domo for healthcare customers. Want to join a small Utah cyber team owning the TEE story.",
    location: 'American Fork, UT',
    email: 'ben.okafor@example.com',
    roleType: 'engineer',
    sectors: ['cyber', 'software'],
    skills: ['confidential compute', 'SGX', 'TEEs', 'HIPAA', 'attestation'],
    functions: ['engineering'],
    availability: 'full_time',
    stagePreference: ['seed', 'series_a'],
    riskTolerance: 'medium',
    compShape: ['salary', 'equity'],
    missionTags: ['productivity', 'patient_outcomes'],
    affiliations: ['domo', 'silicon_slopes'],
    yearsExperience: 9,
  },

  // ---------- Sales / Marketing ----------
  {
    id: 't_riley_white',
    name: 'Riley White',
    headline: 'Enterprise AE · sold into top-10 community banks',
    bio: "10 years selling vertical SaaS into community banks (last at nCino). Closed $4M+ in net-new ARR in 2024. Open to a Utah fintech with an underwriting or treasury product.",
    location: 'Lehi, UT',
    email: 'riley.white@example.com',
    roleType: 'sales',
    sectors: ['fintech', 'software'],
    skills: ['enterprise sales', 'community bank GTM', 'six-figure deal cycles', 'RFP response'],
    functions: ['sales'],
    availability: 'full_time',
    stagePreference: ['series_a', 'series_b'],
    riskTolerance: 'medium',
    compShape: ['salary', 'equity'],
    missionTags: ['productivity'],
    affiliations: ['silicon_slopes'],
    yearsExperience: 10,
  },
  {
    id: 't_grace_lin',
    name: 'Grace Lin',
    headline: 'DoD biz-dev · 7 yrs Air Force PMA Hill AFB',
    bio: "Hill AFB PMA office, then Boeing capture team. Know the DoD program-office buying motion cold. Looking for a Utah defense-tech series A as VP BD.",
    location: 'Layton, UT',
    email: 'grace.lin@example.com',
    roleType: 'sales',
    sectors: ['defense', 'advanced_manufacturing'],
    skills: ['DoD biz dev', 'AFWERX', 'OTAs', 'capture management', 'program office relationships'],
    functions: ['sales', 'operations'],
    availability: 'full_time',
    stagePreference: ['seed', 'series_a'],
    riskTolerance: 'medium',
    compShape: ['salary', 'equity'],
    missionTags: ['defense', 'hard_tech'],
    affiliations: ['silicon_slopes'],
    yearsExperience: 11,
  },
  {
    id: 't_jared_pike',
    name: 'Jared Pike',
    headline: 'Healthcare hospital-systems sales · ex-Intermountain partner',
    bio: "Sold ML/analytics tooling into Intermountain, U of U Health, and Banner. Strong relationships with Utah CMIOs and CMOs. Want to join a Utah healthcare AI seed.",
    location: 'Salt Lake City, UT',
    email: 'jared.pike@example.com',
    roleType: 'sales',
    sectors: ['life_sciences', 'ai'],
    skills: ['health system sales', 'CMIO relationships', 'HIPAA contracting', 'pilot-to-contract conversion'],
    functions: ['sales', 'operations'],
    availability: 'full_time',
    stagePreference: ['seed', 'series_a'],
    riskTolerance: 'medium',
    compShape: ['salary', 'equity'],
    missionTags: ['patient_outcomes'],
    affiliations: ['u_of_u', 'silicon_slopes'],
    yearsExperience: 9,
  },
  {
    id: 't_helena_strom',
    name: 'Helena Strom',
    headline: 'Fractional CMO · category-creation in regulated verticals',
    bio: "Did the category-creation playbook for a series-B fintech and a series-C healthtech. Open to two fractional CMO seats with Utah regulated-vertical companies.",
    location: 'Salt Lake City, UT',
    email: 'helena.strom@example.com',
    roleType: 'fractional',
    sectors: ['fintech', 'life_sciences', 'cyber'],
    skills: ['category creation', 'analyst relations', 'positioning', 'regulated-vertical marketing'],
    functions: ['operations'],
    availability: 'fractional',
    stagePreference: ['seed', 'series_a'],
    riskTolerance: 'medium',
    compShape: ['hourly', 'equity'],
    missionTags: ['productivity', 'patient_outcomes'],
    affiliations: ['silicon_slopes'],
    yearsExperience: 14,
  },
  {
    id: 't_owen_vaughn',
    name: 'Owen Vaughn',
    headline: 'Growth marketer · PLG · ex-Pluralsight + Lucid',
    bio: "Built the lifecycle marketing engine at Pluralsight and Lucid. Want a $1-10M ARR Utah B2B SaaS where I can own demand end-to-end.",
    location: 'South Jordan, UT',
    email: 'owen.vaughn@example.com',
    roleType: 'marketing',
    sectors: ['software', 'fintech'],
    skills: ['PLG', 'lifecycle marketing', 'paid acquisition', 'ABM', 'analytics'],
    functions: ['operations'],
    availability: 'full_time',
    stagePreference: ['seed', 'series_a'],
    riskTolerance: 'medium',
    compShape: ['salary', 'equity'],
    missionTags: ['productivity'],
    affiliations: ['pluralsight', 'silicon_slopes'],
    yearsExperience: 8,
  },

  // ---------- Students / Interns ----------
  {
    id: 't_mira_okonjo',
    name: 'Mira Okonjo',
    headline: 'BYU CS senior · ML/CV · 2 published papers',
    bio: "Last semester at BYU CS, two ICML-workshop papers in remote sensing + ML. Want a research-heavy summer internship at a Utah AI startup, ideally one applying ML to land/agriculture.",
    location: 'Provo, UT',
    email: 'mira.okonjo@example.com',
    roleType: 'student',
    sectors: ['ai'],
    skills: ['Python', 'PyTorch', 'remote sensing', 'computer vision', 'research'],
    functions: ['engineering', 'product'],
    availability: 'internship',
    stagePreference: ['pre_seed', 'seed', 'series_a'],
    riskTolerance: 'high',
    compShape: ['hourly', 'equity'],
    missionTags: ['sustainability', 'deep_science'],
    affiliations: ['byu'],
    yearsExperience: 0,
  },
  {
    id: 't_sam_archer',
    name: 'Sam Archer',
    headline: 'U of U bioE undergrad · wet-lab + microfluidics',
    bio: "Junior at U of U Bioengineering. Two semesters in the Christensen microfluidics lab. Looking for a part-time wet-lab role at a Utah life-sciences startup.",
    location: 'Salt Lake City, UT',
    email: 'sam.archer@example.com',
    roleType: 'student',
    sectors: ['life_sciences'],
    skills: ['microfluidics', 'wet lab', 'Python', 'bioassays'],
    functions: ['engineering'],
    availability: 'internship',
    stagePreference: ['pre_seed', 'seed'],
    riskTolerance: 'high',
    compShape: ['hourly'],
    missionTags: ['patient_outcomes', 'deep_science'],
    affiliations: ['u_of_u'],
    yearsExperience: 0,
  },
  {
    id: 't_rachel_vance',
    name: 'Rachel Vance',
    headline: 'USU MBA candidate · clean tech + project finance',
    bio: "USU MBA candidate (May 2026 graduation), prior 3 years at Rocky Mountain Power. Looking for a summer fellowship at a Utah clean-tech startup focused on commercial deployment.",
    location: 'Logan, UT',
    email: 'rachel.vance@example.com',
    roleType: 'intern',
    sectors: ['energy', 'advanced_manufacturing'],
    skills: ['utility partnerships', 'MBA', 'project finance', 'GTM analysis'],
    functions: ['operations', 'finance'],
    availability: 'internship',
    stagePreference: ['seed', 'series_a'],
    riskTolerance: 'medium',
    compShape: ['hourly'],
    missionTags: ['sustainability'],
    affiliations: ['usu'],
    yearsExperience: 3,
  },
  {
    id: 't_noah_grant',
    name: 'Noah Grant',
    headline: 'BYU mech-E senior · robotics labs · controls',
    bio: "BYU senior in mechanical engineering, focus on controls. Built a competitive autonomous rover, third place at AUVSI 2025. Want a Utah robotics startup internship that turns into full-time.",
    location: 'Provo, UT',
    email: 'noah.grant@example.com',
    roleType: 'student',
    sectors: ['advanced_manufacturing', 'defense'],
    skills: ['controls', 'C++', 'ROS', 'mechatronics', 'robotics competition'],
    functions: ['engineering'],
    availability: 'internship',
    stagePreference: ['pre_seed', 'seed'],
    riskTolerance: 'high',
    compShape: ['hourly', 'equity'],
    missionTags: ['hard_tech'],
    affiliations: ['byu'],
    yearsExperience: 0,
  },

  // ---------- Advisors / Mentors / Board ----------
  {
    id: 't_dr_rashid_lee',
    name: 'Dr. Rashid Lee',
    headline: 'U of U bioE professor · neural interfaces · 100+ pubs',
    bio: "Professor of bioengineering at the U of U. Lab built one of the country's leading research programs on cortical neural interfaces. Open to advisor roles for Utah neural-tech and BCI startups (equity preferred).",
    location: 'Salt Lake City, UT',
    email: 'rashid.lee@example.com',
    roleType: 'advisor',
    sectors: ['life_sciences'],
    skills: ['neural interfaces', 'BCI', 'academic translation', 'NIH grants', 'IP licensing'],
    functions: ['product', 'regulatory'],
    availability: 'advisory',
    stagePreference: ['idea', 'pre_seed', 'seed'],
    riskTolerance: 'low',
    compShape: ['advisor_equity'],
    missionTags: ['deep_science', 'patient_outcomes', 'hard_tech'],
    affiliations: ['u_of_u'],
    yearsExperience: 25,
  },
  {
    id: 't_dr_julia_hart',
    name: 'Dr. Julia Hart',
    headline: 'BYU plant-sciences professor · regen-ag, 30 yrs',
    bio: "BYU professor of plant and wildlife sciences. Three decades of regenerative agriculture research, mostly arid-West rangelands. Mentor (free) for Utah ag-tech and regenerative-ag founders.",
    location: 'Provo, UT',
    email: 'julia.hart@example.com',
    roleType: 'mentor',
    sectors: ['ai'],
    skills: ['regenerative agriculture', 'ecology', 'public-private partnerships', 'BLM relationships'],
    functions: ['product', 'operations'],
    availability: 'mentor',
    stagePreference: ['idea', 'pre_seed', 'seed'],
    riskTolerance: 'low',
    compShape: ['free'],
    missionTags: ['sustainability', 'deep_science'],
    affiliations: ['byu'],
    yearsExperience: 30,
  },
  {
    id: 't_carlos_renteria',
    name: 'Carlos Renteria',
    headline: 'Independent board director · 4 boards (3 Utah, 1 Bay Area)',
    bio: "Sits on four boards. Comp scaled to small companies — happy to take board seats from Utah seed/series-A companies. Special interest in deep tech and dual-use defense.",
    location: 'Heber City, UT',
    email: 'carlos.renteria@example.com',
    roleType: 'board',
    sectors: ['defense', 'cyber', 'fintech'],
    skills: ['board governance', 'audit committee', 'CEO succession', 'M&A'],
    functions: ['operations', 'finance'],
    availability: 'advisory',
    stagePreference: ['series_a', 'series_b'],
    riskTolerance: 'medium',
    compShape: ['advisor_equity', 'salary'],
    missionTags: ['defense', 'hard_tech', 'productivity'],
    affiliations: ['silicon_slopes'],
    yearsExperience: 22,
  },
  {
    id: 't_natalie_okada',
    name: 'Natalie Okada',
    headline: 'Healthcare regulatory advisor · ex-FDA medical-device reviewer',
    bio: "Twelve years at FDA CDRH as a Class II/III device reviewer, now an independent regulatory consultant. Take 1-2 advisor seats per year, equity-preferred.",
    location: 'Park City, UT',
    email: 'natalie.okada@example.com',
    roleType: 'advisor',
    sectors: ['life_sciences'],
    skills: ['FDA CDRH', '510k', 'PMA', 'Q-Sub', 'design controls'],
    functions: ['regulatory'],
    availability: 'advisory',
    stagePreference: ['pre_seed', 'seed', 'series_a'],
    riskTolerance: 'low',
    compShape: ['advisor_equity', 'hourly'],
    missionTags: ['patient_outcomes', 'deep_science'],
    affiliations: ['park_city'],
    yearsExperience: 15,
  },
  {
    id: 't_kev_armstrong',
    name: 'Kev Armstrong',
    headline: 'Mentor (free) · 3x cofounder · Silicon Slopes OG',
    bio: "Cofounded three SaaS companies, two exits. Now retired, mentor 4-5 Utah founders for free. Best with first-time founders going pre-seed to seed.",
    location: 'Lehi, UT',
    email: 'kev.armstrong@example.com',
    roleType: 'mentor',
    sectors: ['software', 'fintech', 'cyber'],
    skills: ['first-time founder coaching', 'fundraising', 'pricing', 'sales'],
    functions: ['operations'],
    availability: 'mentor',
    stagePreference: ['idea', 'pre_seed', 'seed'],
    riskTolerance: 'low',
    compShape: ['free'],
    missionTags: ['productivity'],
    affiliations: ['silicon_slopes'],
    yearsExperience: 20,
  },

  // ---------- More executives + specialists to fill out the catalog ----------
  {
    id: 't_alex_sun',
    name: 'Alex Sun',
    headline: 'CTO · agentic systems · ex-Anthropic deployment lead',
    bio: "Two years at Anthropic on the deployments team. Want a Utah AI startup founding-CTO seat where the tech stack is an open question.",
    location: 'Lehi, UT',
    email: 'alex.sun@example.com',
    roleType: 'executive',
    sectors: ['ai', 'cyber', 'software'],
    skills: ['LLM systems', 'agentic architectures', 'RAG', 'evals', 'distributed systems'],
    functions: ['engineering', 'product'],
    availability: 'full_time',
    stagePreference: ['idea', 'pre_seed', 'seed'],
    riskTolerance: 'high',
    compShape: ['equity', 'salary'],
    missionTags: ['hard_tech', 'productivity'],
    affiliations: ['silicon_slopes'],
    yearsExperience: 9,
  },
  {
    id: 't_lila_hashimoto',
    name: 'Lila Hashimoto',
    headline: 'Head of clinical ops · ex-Recursion · oncology trials',
    bio: "Built and ran the clinical ops team at Recursion's first-in-human program. Wants to join a Utah oncology-focused company at the IND-enabling stage.",
    location: 'Salt Lake City, UT',
    email: 'lila.hashimoto@example.com',
    roleType: 'executive',
    sectors: ['life_sciences'],
    skills: ['clinical ops', 'CRO management', 'first-in-human trials', 'oncology'],
    functions: ['operations', 'regulatory'],
    availability: 'full_time',
    stagePreference: ['seed', 'series_a'],
    riskTolerance: 'medium',
    compShape: ['salary', 'equity'],
    missionTags: ['patient_outcomes', 'deep_science'],
    affiliations: ['recursion', 'u_of_u'],
    yearsExperience: 11,
  },
  {
    id: 't_quinn_blair',
    name: 'Quinn Blair',
    headline: 'NRC regulatory specialist · advanced reactor pre-app filings',
    bio: "Eight years at NRC, then INL nuclear regulatory affairs. Niche expertise in advanced-reactor pre-application engagements. Open to a Utah/Idaho energy startup full-time or fractional.",
    location: 'Idaho Falls, ID',
    email: 'quinn.blair@example.com',
    roleType: 'fractional',
    sectors: ['energy', 'defense'],
    skills: ['NRC pre-application', 'advanced reactor licensing', 'Part 50/52'],
    functions: ['regulatory'],
    availability: 'fractional',
    stagePreference: ['seed', 'series_a', 'series_b'],
    riskTolerance: 'medium',
    compShape: ['hourly', 'equity'],
    missionTags: ['hard_tech', 'sustainability', 'defense'],
    affiliations: ['silicon_slopes'],
    yearsExperience: 12,
  },
  {
    id: 't_evan_holt',
    name: 'Evan Holt',
    headline: 'Head of Customer Success · vertical SaaS · scaled franchises',
    bio: "Ran CS at a 200-customer vertical SaaS company through acquisition. Want a similar-shape Utah company growing through services-heavy verticals.",
    location: 'Bluffdale, UT',
    email: 'evan.holt@example.com',
    roleType: 'executive',
    sectors: ['software'],
    skills: ['customer success', 'NRR', 'services-heavy SaaS', 'franchise verticals'],
    functions: ['operations', 'sales'],
    availability: 'full_time',
    stagePreference: ['series_a', 'growth'],
    riskTolerance: 'medium',
    compShape: ['salary', 'equity'],
    missionTags: ['productivity'],
    affiliations: ['silicon_slopes'],
    yearsExperience: 12,
  },
  {
    id: 't_juno_park',
    name: 'Juno Park',
    headline: 'Head of family-office BD · 3 Utah RIA relationships',
    bio: "Eight years at a Utah RIA, deep relationships across Park City and Salt Lake family offices. Open to a fractional BD seat at a Utah fintech serving the wealth segment.",
    location: 'Park City, UT',
    email: 'juno.park@example.com',
    roleType: 'fractional',
    sectors: ['fintech'],
    skills: ['family-office BD', 'RIA partnerships', 'wealth-tech sales'],
    functions: ['sales'],
    availability: 'fractional',
    stagePreference: ['pre_seed', 'seed'],
    riskTolerance: 'medium',
    compShape: ['hourly', 'equity'],
    missionTags: ['productivity'],
    affiliations: ['park_city'],
    yearsExperience: 11,
  },
  {
    id: 't_ramon_villa',
    name: 'Ramon Villa',
    headline: 'Senior product · agentic identity · ex-Okta',
    bio: "Eight years senior PM at Okta on machine identity and agentic identity products. Want to join a Utah cyber seed building in the same space.",
    location: 'Lehi, UT',
    email: 'ramon.villa@example.com',
    roleType: 'engineer',
    sectors: ['cyber', 'software'],
    skills: ['product management', 'machine identity', 'agentic identity', 'IAM'],
    functions: ['product'],
    availability: 'full_time',
    stagePreference: ['pre_seed', 'seed'],
    riskTolerance: 'high',
    compShape: ['salary', 'equity'],
    missionTags: ['hard_tech', 'productivity'],
    affiliations: ['silicon_slopes'],
    yearsExperience: 12,
  },
  {
    id: 't_anika_shah',
    name: 'Anika Shah',
    headline: 'Junior analyst · BYU finance · alts + family office',
    bio: "BYU finance senior. Internships at Goldman PWM and a Park City single-family office. Looking for an analyst seat at a Utah fintech serving alts.",
    location: 'Provo, UT',
    email: 'anika.shah@example.com',
    roleType: 'intern',
    sectors: ['fintech'],
    skills: ['Excel', 'alts accounting', 'financial modeling', 'CFA L1'],
    functions: ['finance', 'operations'],
    availability: 'internship',
    stagePreference: ['pre_seed', 'seed'],
    riskTolerance: 'medium',
    compShape: ['salary', 'hourly'],
    missionTags: ['productivity'],
    affiliations: ['byu', 'park_city'],
    yearsExperience: 1,
  },
  {
    id: 't_morgan_ash',
    name: 'Morgan Ash',
    headline: 'Pediatric oncology PhD · Huntsman Cancer Institute',
    bio: "Postdoc at Huntsman Cancer Institute, focus on diffuse midline glioma. Open to a chief medical officer or chief scientist seat at a Utah pediatric-onc startup.",
    location: 'Salt Lake City, UT',
    email: 'morgan.ash@example.com',
    roleType: 'executive',
    sectors: ['life_sciences'],
    skills: ['pediatric oncology', 'CNS tumors', 'translational research', 'NIH grants'],
    functions: ['product', 'regulatory'],
    availability: 'full_time',
    stagePreference: ['seed', 'series_a'],
    riskTolerance: 'high',
    compShape: ['salary', 'equity'],
    missionTags: ['patient_outcomes', 'deep_science'],
    affiliations: ['u_of_u'],
    yearsExperience: 8,
  },

  // ---------- Angel Investors / VCs ----------
  {
    id: 't_amelia_redford',
    name: 'Amelia Redford',
    headline: 'Solo GP · seed-stage life sciences · 14 Utah deep-tech checks',
    bio: "Solo GP at Wasatch Bio Capital. Writes $250k–$1.5M seed checks, lead or co-lead. Thesis: Utah-rooted life-sciences and bioengineering — especially anything coming out of Huntsman, U of U, or Recursion alumni founders. 14 active portfolio companies; led the seed in two recent FDA Breakthrough designees.",
    location: 'Salt Lake City, UT',
    email: 'amelia@wasatchbio.example.com',
    roleType: 'investor',
    sectors: ['life_sciences'],
    skills: ['seed checks $250k-1.5M', 'lead or co-lead', 'FDA reg pathway diligence', 'board seats', 'follow-on reserves', 'Utah deep-tech thesis'],
    functions: ['finance'],
    availability: 'advisory',
    stagePreference: ['pre_seed', 'seed'],
    riskTolerance: 'high',
    compShape: ['equity'],
    missionTags: ['patient_outcomes', 'deep_science'],
    affiliations: ['u_of_u', 'recursion'],
    yearsExperience: 11,
  },
  {
    id: 't_carlos_renteria_vc',
    name: 'Carlos Rentería',
    headline: 'Partner · Wasatch Frontier · defense + advanced manufacturing',
    bio: "Partner at Wasatch Frontier, a Utah-focused fund writing $500k–$3M Series A checks in defense, aerospace, and advanced manufacturing. Former Sarcos exec. Looks for hardware companies with at least one DoD program of record or a credible path to one. Strong on production-readiness diligence.",
    location: 'Park City, UT',
    email: 'carlos@wasatchfrontier.example.com',
    roleType: 'investor',
    sectors: ['defense', 'advanced_manufacturing'],
    skills: ['Series A checks $500k-3M', 'DoD program diligence', 'production-readiness diligence', 'follow-on reserves', 'board observer'],
    functions: ['finance', 'operations'],
    availability: 'advisory',
    stagePreference: ['seed', 'series_a'],
    riskTolerance: 'high',
    compShape: ['equity'],
    missionTags: ['defense', 'hard_tech'],
    affiliations: ['sarcos', 'silicon_slopes'],
    yearsExperience: 16,
  },

  // ---------- Service Providers ----------
  {
    id: 't_kara_levitt',
    name: 'Kara Levitt',
    headline: 'FDA regulatory counsel · 12 IND filings · solo practice',
    bio: "Solo regulatory attorney specializing in pre-IND meetings, IND submissions, and Class III device pathways. Twelve IND filings over the last six years, mostly Utah and Bay Area life-sciences clients. Flat-fee or retainer for early-stage; comfortable taking part of the engagement in equity for pre-seed companies with strong fundamentals.",
    location: 'Salt Lake City, UT',
    email: 'kara@levittreg.example.com',
    roleType: 'service_provider',
    sectors: ['life_sciences'],
    skills: ['FDA regulatory law', 'IND filings', 'pre-IND meetings', 'Class III device pathway', 'flat-fee engagements', 'equity-for-services'],
    functions: ['legal', 'regulatory'],
    availability: 'fractional',
    stagePreference: ['pre_seed', 'seed', 'series_a'],
    riskTolerance: 'medium',
    compShape: ['salary', 'equity'],
    missionTags: ['patient_outcomes', 'deep_science'],
    affiliations: [],
    yearsExperience: 9,
  },
  {
    id: 't_studio_meridian',
    name: 'Jude Petersen (Studio Meridian)',
    headline: 'Brand & narrative for deep-tech founders · 30+ Utah startups',
    bio: "Two-person creative studio that does naming, brand identity, and pitch-narrative work for Utah deep-tech and life-sciences startups. Past clients include three Recursion alumni companies and two BYU spinouts. Specialty: turning a dense scientific story into a 90-second investor narrative without losing the rigor.",
    location: 'Provo, UT',
    email: 'hello@studiomeridian.example.com',
    roleType: 'service_provider',
    sectors: ['life_sciences', 'ai', 'advanced_manufacturing'],
    skills: ['brand identity', 'naming', 'pitch deck narrative', 'investor narrative coaching', 'website design'],
    functions: ['marketing', 'product'],
    availability: 'fractional',
    stagePreference: ['pre_seed', 'seed', 'series_a'],
    riskTolerance: 'medium',
    compShape: ['salary'],
    missionTags: ['hard_tech', 'deep_science'],
    affiliations: ['byu', 'recursion'],
    yearsExperience: 12,
  },
];
